In [6]:
import numpy as np

# Constructing a matrix
matrix = np.array([
    [1, 0.2, 0.5],
    [0.2, 1, 0.8],
    [0.5, 0.8, 1]
])


In [9]:
#Determinant of a matrix
determinant= np.linalg.det(matrix)
print(determinant)

0.2299999999999999


In [13]:
#Decomposing the matrix
import numpy as np
from scipy.linalg import lu

# Constructing a matrix
matrix = np.array([
    [1, 0.2, 0.5],
    [0.2, 1, 0.8],
    [0.5, 0.8, 1]
])
#performing lower and upper triangular matrix decomposition
P, L, U = lu(matrix)

print(f"Original Matrix is ")
print(matrix)

print(f"Lower Triangular Matrix is ")
print(L)

print(f"Upper Triangular Matrix is")
print(U)


Original Matrix is 
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]
Lower Triangular Matrix is 
[[1.         0.         0.        ]
 [0.2        1.         0.        ]
 [0.5        0.72916667 1.        ]]
Upper Triangular Matrix is
[[1.         0.2        0.5       ]
 [0.         0.96       0.7       ]
 [0.         0.         0.23958333]]


In [14]:
#transforming a matrix
transformed_matrix= np.transpose(matrix)
print(transformed_matrix)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]
